### ISSUE TITLE
Multiclass Classification using ProtoTEx

### ISSUE THREAD

**Issue by himanshurawlani** [anubrata/ProtoTEx#2]
Congratulations on your work on "ProtoTex: Explaining Model Decisions with Prototype Tensors". It is exciting to see the novel interleaved training approach for negative prototype and the excellent accuracy of ProtoTEx on the classification task.

After going through your GitHub implementation, I realize that the code is very specific for the binary classification task. However, your research paper has discussed results for multiclass classification on 18 classes of propaganda detection dataset. Would it be possible for you to share the code for multiclass classification?

**Comment by anubrata** [comment]
Hi Himanshu, thanks for reaching out. Unfortunately, we did not implement a multiclass classifier. We used the 18 subclasses of propaganda and turned that into a binary classification task.
